In [1]:
import numpy as np

In [2]:
vec = np.array([1,2,3]) # A simple 3D vector

In [3]:
type(vec)

numpy.ndarray

In [4]:
vec.shape

(3,)

In [7]:
print(vec[:2])
print(vec[-3:])
print(vec[1:3])

[1 2]
[1 2 3]
[2 3]


#### Lists are fine for storage but vectors in numpy are designed for mathematical operations
#### Like using a plus or multiply operator in lists just repeats the lists. But in numpy does actual operations are performed.

### Vectorised Operations

In [10]:
vec = np.array([1,2,3])
other = np.array([6,5,4])

# Element wise operations

print(vec+ other)
print(vec * 2)
print(vec ** 2)

[7 7 7]
[2 4 6]
[1 4 9]


In [14]:
 np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Aggregations

In [20]:
print(np.sum(vec))
print(np.mean(vec))
print(np.std(vec))

6
2.0
0.816496580927726


In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [22]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [25]:
np.arange(11,122,11)

array([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121])

In [27]:
np.linspace(0,1,5) # Creates an array of evenly spaced numbers over a specified interval

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.linspace(0,100,9)

array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [37]:
np.random.rand(3) # Random 3D Vector

array([0.59455112, 0.70860485, 0.79248711])