# Pytorch

## Creating vectors as pytorch tensors

### A tensor is a generalization of vectors and matrices to potentially n number of dimensions

In [1]:
import torch

In [2]:
vec = torch.tensor([1.0,2.,3.0]) # 3D Vector

In [3]:
type(vec)

torch.Tensor

### Shape and indexing

In [4]:
print(vec.shape) # torch.size([3])
print(vec[0]) # tensor(1.)
print(vec[-1]) # tensor(3.)
print(vec[1:]) # tensor(2.,3.)

torch.Size([3])
tensor(1.)
tensor(3.)
tensor([2., 3.])


### Vectorised Operations

In [5]:
other = torch.tensor([4.0,5.0,6.0])

print(vec+other) # tensor([5.,7.,9.])
print(vec * 2) # tensor([2.,6.,8.])
print(vec ** 2) # tensor([1.,4.,9.])

tensor([5., 7., 9.])
tensor([2., 4., 6.])
tensor([1., 4., 9.])


### Aggregations

In [6]:
print(vec.sum())
print(vec.mean())
print(vec.std())

tensor(6.)
tensor(2.)
tensor(1.)


### Quick Creations

In [7]:
torch.zeros(3)

tensor([0., 0., 0.])

In [8]:
torch.ones(3)

tensor([1., 1., 1.])

In [9]:
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [10]:
torch.linspace(0,1,5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [11]:
torch.rand(3)

tensor([0.9327, 0.0175, 0.9239])

### Whether you are using numpy or pytorch, creating a vector is just about bundling multiple numbers together into one object

In [14]:
scalar = torch.tensor(7.0) # Tensor with 0 dimensions

In [15]:
scalar

tensor(7.)

In [17]:
vector = torch.tensor([1.0,2.0,3.0]) # Passing a list creates a tensor of one dimensional vector
vector

tensor([1., 2., 3.])

In [18]:
## A matrix is a list of lists.

matrix = torch.tensor([[1,2],[3,4]])

In [21]:
print(matrix)

tensor([[1, 2],
        [3, 4]])


In [26]:
tensor3d = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]]

],
dtype=torch.float32)

In [27]:
tensor3d

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

#### The level of nesting determines the rank of the tensor

In [24]:
matrix.dtype

torch.int64

In [25]:
vector.dtype

torch.float32

In [28]:
tensor3d.dtype

torch.float32

In [30]:
print(torch.zeros(4,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [31]:
print(torch.zeros(4,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [39]:
print(torch.zeros(5,2,3,4))

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


In [42]:
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [45]:
print(torch.full((5,5),7))

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])


In [48]:
print(torch.eye(3) * 9)

tensor([[9., 0., 0.],
        [0., 9., 0.],
        [0., 0., 9.]])


In [50]:
print(torch.rand(3,2))

tensor([[0.7541, 0.7270],
        [0.5087, 0.6257],
        [0.5586, 0.3681]])


In [52]:
print(torch.randn(3,2)) # randn picks up the value from a normal distribution

tensor([[ 0.3559, -0.7556],
        [ 0.1583,  0.2582],
        [ 1.3856,  1.5155]])


In [54]:
val = torch.randn(3,2)

In [56]:
print(val)

tensor([[ 0.5341, -0.5011],
        [ 1.7123,  1.1546],
        [ 0.9367,  0.4066]])


In [57]:
sum(val)

tensor([3.1831, 1.0601])

In [58]:
t = torch.randn(3,4)

In [59]:
t.shape # .shape tells us the size of the tensor in each dimension.

torch.Size([3, 4])

In [63]:
t.ndim # .ndim gives us the number of dimensions, which is also the rank of the tensor.

2

In [64]:
t.numel() # gives the total number of elements in the tensor.

12

In [66]:
t.device # by default they are created on cpus

device(type='cpu')

In [68]:
t_gpu = t.to("cuda")

AssertionError: Torch not compiled with CUDA enabled