# Pytorch

## Creating vectors as pytorch tensors

### A tensor is a generalization of vectors and matrices to potentially n number of dimensions

In [1]:
import torch

In [2]:
vec = torch.tensor([1.0,2.,3.0]) # 3D Vector

In [3]:
type(vec)

torch.Tensor

### Shape and indexing

In [4]:
print(vec.shape) # torch.size([3])
print(vec[0]) # tensor(1.)
print(vec[-1]) # tensor(3.)
print(vec[1:]) # tensor(2.,3.)

torch.Size([3])
tensor(1.)
tensor(3.)
tensor([2., 3.])


### Vectorised Operations

In [5]:
other = torch.tensor([4.0,5.0,6.0])

print(vec+other) # tensor([5.,7.,9.])
print(vec * 2) # tensor([2.,6.,8.])
print(vec ** 2) # tensor([1.,4.,9.])

tensor([5., 7., 9.])
tensor([2., 4., 6.])
tensor([1., 4., 9.])


### Aggregations

In [6]:
print(vec.sum())
print(vec.mean())
print(vec.std())

tensor(6.)
tensor(2.)
tensor(1.)


### Quick Creations

In [7]:
torch.zeros(3)

tensor([0., 0., 0.])

In [8]:
torch.ones(3)

tensor([1., 1., 1.])

In [9]:
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [10]:
torch.linspace(0,1,5)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [11]:
torch.rand(3)

tensor([0.9327, 0.0175, 0.9239])

### Whether you are using numpy or pytorch, creating a vector is just about bundling multiple numbers together into one object

In [14]:
scalar = torch.tensor(7.0) # Tensor with 0 dimensions

In [15]:
scalar

tensor(7.)

In [17]:
vector = torch.tensor([1.0,2.0,3.0]) # Passing a list creates a tensor of one dimensional vector
vector

tensor([1., 2., 3.])

In [18]:
## A matrix is a list of lists.

matrix = torch.tensor([[1,2],[3,4]])

In [21]:
print(matrix)

tensor([[1, 2],
        [3, 4]])


In [26]:
tensor3d = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]]

],
dtype=torch.float32)

In [27]:
tensor3d

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

#### The level of nesting determines the rank of the tensor

In [24]:
matrix.dtype

torch.int64

In [25]:
vector.dtype

torch.float32

In [28]:
tensor3d.dtype

torch.float32

In [30]:
print(torch.zeros(4,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [31]:
print(torch.zeros(4,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [39]:
print(torch.zeros(5,2,3,4))

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])


In [42]:
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [45]:
print(torch.full((5,5),7))

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])


In [48]:
print(torch.eye(3) * 9)

tensor([[9., 0., 0.],
        [0., 9., 0.],
        [0., 0., 9.]])


In [50]:
print(torch.rand(3,2))

tensor([[0.7541, 0.7270],
        [0.5087, 0.6257],
        [0.5586, 0.3681]])


In [52]:
print(torch.randn(3,2)) # randn picks up the value from a normal distribution

tensor([[ 0.3559, -0.7556],
        [ 0.1583,  0.2582],
        [ 1.3856,  1.5155]])


In [54]:
val = torch.randn(3,2)

In [56]:
print(val)

tensor([[ 0.5341, -0.5011],
        [ 1.7123,  1.1546],
        [ 0.9367,  0.4066]])


In [57]:
sum(val)

tensor([3.1831, 1.0601])

In [58]:
t = torch.randn(3,4)

In [59]:
t.shape # .shape tells us the size of the tensor in each dimension.

torch.Size([3, 4])

In [63]:
t.ndim # .ndim gives us the number of dimensions, which is also the rank of the tensor.

2

In [64]:
t.numel() # gives the total number of elements in the tensor.

12

In [66]:
t.device # by default they are created on cpus

device(type='cpu')

In [68]:
t_gpu = t.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [71]:
scalar = torch.tensor(42.0)
type(scalar)

torch.Tensor

In [72]:
value = scalar.item() # Gives the python value
type(value)

float

In [73]:
vector = torch.tensor([1.0,2.0,3.0])

In [75]:
vector.numpy() # Convert a pytorch tensor to a numpy array

array([1., 2., 3.], dtype=float32)

In [77]:
import numpy as np

In [82]:
numpy_matrix = np.array([[10,20,30],[40,50,60]])
type(numpy_matrix)

numpy.ndarray

In [84]:
type(torch.from_numpy(numpy_matrix)) # Converts numpy array to pytorch tensor
# This shares memory with the original variable.

torch.Tensor

### Use torch.tensor() - Not torch.Tensor()

In [85]:
torch.tensor([1,2,3]) # This is preferred, it infers shape and type properly.

tensor([1, 2, 3])

In [87]:
type(torch.tensor([1,2,3]))

torch.Tensor

In [89]:
torch.Tensor([1,2,3]) # it is a low level constructor and often creates uninitialized memory

tensor([1., 2., 3.])

In [88]:
type(torch.Tensor([1,2,3]))

torch.Tensor

In [90]:
t.shape

torch.Size([3, 4])

In [91]:
t.ndim

2

#### Never mix cpu & gpu based tensor in operations

## Manipulating Tensors: Creating, Slicing, Inspecting

### Basic Indexing

In [93]:
import torch
# Let's consider a simple matrix of 2 rows and 3 columns.
t = torch.tensor([[10,20,30],
                  [40,50,60]])

#### Indexing
#### Helps us extract elements like rows, columns or subtensors

In [94]:
t[0]

tensor([10, 20, 30])

In [97]:
t[0][2]

tensor(30)

In [99]:
t[1,2] # Preferred syntax

tensor(60)

#### Slicing with ranges

In [102]:
t[:,1]

tensor([20, 50])

In [106]:
t[:,1:] # All rows and column 1 to end of our tensor will be extracted

tensor([[20, 30],
        [50, 60]])

In [108]:
t[:,:1] # All rows and until column 1 will be extracted

tensor([[10],
        [40]])

In [110]:
t[1:,:2] # From 1st row onwards till end for the first 2 columns will be extracted

tensor([[40, 50]])

In [113]:
t = torch.rand(5,3)

In [114]:
t

tensor([[0.3804, 0.5170, 0.0836],
        [0.1670, 0.6146, 0.9535],
        [0.5341, 0.3679, 0.9148],
        [0.6938, 0.7642, 0.5580],
        [0.1340, 0.6843, 0.9516]])

In [115]:
# Can also include steps to slice from

# This will extract every 2nd row
t[::2]

tensor([[0.3804, 0.5170, 0.0836],
        [0.5341, 0.3679, 0.9148],
        [0.1340, 0.6843, 0.9516]])

In [118]:
# Negative Indexing
t[-1] # Extracts the last row

tensor([0.1340, 0.6843, 0.9516])

In [119]:
t

tensor([[0.3804, 0.5170, 0.0836],
        [0.1670, 0.6146, 0.9535],
        [0.5341, 0.3679, 0.9148],
        [0.6938, 0.7642, 0.5580],
        [0.1340, 0.6843, 0.9516]])

In [121]:
t[:,-1] ## Extracts last column

tensor([0.0836, 0.9535, 0.9148, 0.5580, 0.9516])

#### Using ... (Ellipsis)

In [122]:
# it is a powerful shortcut. Imagine a for dimension tensor like the one we have here,

x= torch.randn(2,2,2,2)

In [123]:
x

tensor([[[[ 1.0435,  0.4778],
          [-0.8849,  1.9661]],

         [[ 1.0018,  0.7728],
          [-0.9016, -1.3045]]],


        [[[ 0.1634, -0.3060],
          [ 1.0525,  2.2104]],

         [[ 0.3884, -0.2120],
          [ 0.2092, -1.9681]]]])

In [124]:
# now to select 1st column of every matrix, we can just specify x ellipses comma 0
x[...,0]

tensor([[[ 1.0435, -0.8849],
         [ 1.0018, -0.9016]],

        [[ 0.1634,  1.0525],
         [ 0.3884,  0.2092]]])

In [125]:
myval = x[...,0] # Ellipsis means it helps to avoid wiring a lot of colons when accessing

In [127]:
myval.size()

torch.Size([2, 2, 2])

### Masking
#### Filtering tensor values using boolean conditions

In [129]:
# We don't want to just slice it, but extract values based on the content.
v = torch.tensor([1,2,3,4,5])

In [130]:
mask = v > 3

In [131]:
mask

tensor([False, False, False,  True,  True])

In [132]:
v %2 == 0 # To select even numbers

tensor([False,  True, False,  True, False])

In [134]:
v[v%2 == 0]

tensor([2, 4])

In [135]:
v[v%2 == 1]

tensor([1, 3, 5])

In [136]:
# Conditions can also be stored and reused.

even_mask = (v%2 == 0)

In [137]:
v[even_mask]

tensor([2, 4])

In [139]:
mask

tensor([False, False, False,  True,  True])

In [140]:
mask = [True, False]

In [142]:
v[mask]
## Boolean mask must have the same shape of the dimension we are indexing.

IndexError: The shape of the mask [2] at index 0 does not match the shape of the indexed tensor [5] at index 0

### Reshaping & View
#### Reshaping lets you change the layout of a tensor without changing the underlying data.

In [143]:
t = torch.arange(12)

In [144]:
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
t_reshaped = t.reshape(3,4)

In [146]:
t_reshaped

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [147]:
# Same can be done using view method.

t_viewed = t.view(3,4)

In [148]:
t_viewed

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [149]:
# Reshape and viewed both do the same, but .reshape is more flexible method and .view is slightly faster

In [151]:
t_reshaped.reshape(-1) # is a shorthand to flatten a 1D vector
# regardless of its original shape,  the number of elements must remain same when you are reshapping

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [155]:
t_reshaped.reshape(5,3)
# expected error when the reshaping doesn't meet the total elements count.

RuntimeError: shape '[5, 3]' is invalid for input of size 12

### Adding or Removing Dimensions

In [156]:
v = torch.tensor([1.0,2.0,3.0])

In [157]:
v.shape

torch.Size([3])

In [158]:
# use unsqueezed method to add a dimension of size 1
# to convert to 2d vector.

v_unsq = v.unsqueeze(0)
# this now converts the size from 1 x 3

In [159]:
v_unsq

tensor([[1., 2., 3.]])

In [162]:
type(v_unsq)


torch.Tensor

In [161]:
v_unsq.shape

torch.Size([1, 3])

In [164]:
v_unsq = v.unsqueeze(1)
# to convert to 3 x 1

In [165]:
v_unsq.shape

torch.Size([3, 1])

In [166]:
v_unsq

tensor([[1.],
        [2.],
        [3.]])

In [168]:
# to go back, you can use .squeeze method.
# squeeze method removes all dimensions in the tensor that have a size 1
v_unsq.squeeze()

tensor([1., 2., 3.])

#### To summarize, we use reshape or view to change the shape and squeeze and unsqueeze to control the number of dimensions.

#### Transpose or permute to reorder the dimensions.

In [169]:
m = torch.tensor([[1,2],
                  [3,4]
])

In [173]:
print(m)

tensor([[1, 2],
        [3, 4]])


In [171]:
m.size()

torch.Size([2, 2])

In [172]:
m.shape

torch.Size([2, 2])

In [175]:
print(m.T)

tensor([[1, 3],
        [2, 4]])


In [176]:
# .transpose(dim1, dim2)

t= torch.randn(2,3,4)

In [177]:
t

tensor([[[-0.3833, -0.5715,  0.2091,  1.4770],
         [ 2.0306, -0.7267, -0.3420, -0.9453],
         [-0.9813,  1.3105,  0.0776, -0.4424]],

        [[-0.5071,  1.3319, -0.9020, -2.0356],
         [-0.0244,  0.0156, -2.3400, -1.1837],
         [ 0.9360,  0.4637,  0.4529,  1.3952]]])

In [179]:
t.size()

torch.Size([2, 3, 4])

In [183]:
val2 = t.transpose(1,2)

In [184]:
val2

tensor([[[-0.3833,  2.0306, -0.9813],
         [-0.5715, -0.7267,  1.3105],
         [ 0.2091, -0.3420,  0.0776],
         [ 1.4770, -0.9453, -0.4424]],

        [[-0.5071, -0.0244,  0.9360],
         [ 1.3319,  0.0156,  0.4637],
         [-0.9020, -2.3400,  0.4529],
         [-2.0356, -1.1837,  1.3952]]])

In [185]:
val2.size()

torch.Size([2, 4, 3])

In [186]:
# this is useful when our model or library expects dimensions in a different order.

### Permute
#### Use permute to completely reorder the dimensions.

In [188]:
t = torch.randn(2,3,4)

In [189]:
t

tensor([[[ 2.1616, -0.5871, -0.9930,  1.2083],
         [ 0.3896, -0.7128, -0.1248,  0.3212],
         [ 1.8046, -1.5825, -1.5857, -0.7815]],

        [[-0.3154,  0.2106,  0.3306,  0.1851],
         [-0.9259, -0.8557, -1.6866,  0.4612],
         [ 0.4784, -1.6024,  0.2834, -1.1194]]])

In [190]:
t.size()

torch.Size([2, 3, 4])

In [191]:
t.permute(0,2,1).shape

torch.Size([2, 4, 3])

In [192]:
val3 = t.permute(0,2,1)

In [193]:
val3

tensor([[[ 2.1616,  0.3896,  1.8046],
         [-0.5871, -0.7128, -1.5825],
         [-0.9930, -0.1248, -1.5857],
         [ 1.2083,  0.3212, -0.7815]],

        [[-0.3154, -0.9259,  0.4784],
         [ 0.2106, -0.8557, -1.6024],
         [ 0.3306, -1.6866,  0.2834],
         [ 0.1851,  0.4612, -1.1194]]])

In [194]:
val3.size()

torch.Size([2, 4, 3])

### .expand() - No data copy
#### To expand or repeat data without copying.

In [195]:
x = torch.tensor([[1],
                  [2],
                  [3]])

In [196]:
x.shape

torch.Size([3, 1])

In [197]:
x_expanded = x.expand(3,4)

In [199]:
x_expanded # this is memory efficient, where it creates a view and not a new tensor

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

### .repeat()
#### Makes Actual Copies

In [200]:
x_repeated = x.repeat(1,4)

In [201]:
x_repeated # Creates brand new tensor with values. Slower as uses memory.

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])